<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Role;
use Spatie\Permission\Models\Permission;

class RolesAndPermissionsSeeder extends Seeder
{
    public function run(): void
    {
        // Reset cached roles and permissions
        app()[\Spatie\Permission\PermissionRegistrar::class]->forgetCachedPermissions();

        // Shield generates top-level resource permissions. Relation-manager and
        // workflow permissions remain explicit so they are assignable in Roles.
        $customDomainPermissions = [
            'approve_property_acquisition',
            'cancel_property_acquisition',
            'complete_property_acquisition',
            'view_any_acquisition_property',
            'view_acquisition_property',
            'create_acquisition_property',
            'update_acquisition_property',
            'delete_acquisition_property',
            'view_any_acquisition_party',
            'view_acquisition_party',
            'create_acquisition_party',
            'update_acquisition_party',
            'delete_acquisition_party',
            'view_any_property_ownership',
            'view_property_ownership',
            'change_property_ownership',
            'view_any_due_diligence_case',
            'view_due_diligence_case',
            'create_due_diligence_case',
            'update_due_diligence_case',
            'delete_due_diligence_case',
            'clear_due_diligence_case',
            'view_any_due_diligence_item',
            'view_due_diligence_item',
            'create_due_diligence_item',
            'update_due_diligence_item',
            'delete_due_diligence_item',
            'waive_due_diligence_item',
            'approve_project',
            'cancel_project',
            'close_project',
            'manage_project_members',
            'attach_project_property',
            'detach_project_property',
            'view_any_project_property',
            'view_project_property',
            'view_any_project_member',
            'view_project_member',
            'view_any_project_building',
            'view_project_building',
            'create_project_building',
            'update_project_building',
            'delete_project_building',
            'view_any_project_building_floor',
            'view_project_building_floor',
            'create_project_building_floor',
            'update_project_building_floor',
            'delete_project_building_floor',
            'view_any_project_planned_unit',
            'view_project_planned_unit',
            'create_project_planned_unit',
            'update_project_planned_unit',
            'delete_project_planned_unit',
            'approve_planned_unit',
            'cancel_planned_unit',
            'view_any_planned_unit_specification',
            'view_planned_unit_specification',
            'create_planned_unit_specification',
            'update_planned_unit_specification',
            'delete_planned_unit_specification',
            // Phase 03 — Design / engineering workflow children. ProjectDesignPackage
            // itself is a hidden top-level Filament resource and is generated by Shield.
            'assign_design_package',
            'replace_design_assignment',
            'submit_design_package',
            'review_design_submission',
            'create_design_finding',
            'waive_design_finding',
            'request_design_revision',
            'submit_design_revision',
            'approve_design_package',
            'close_design_package',
            'view_any_document_version', 'view_document_version', 'create_document_version',
            'view_any_design_package_assignment', 'view_design_package_assignment', 'create_design_package_assignment', 'update_design_package_assignment',
            'view_any_design_package_scope_item', 'view_design_package_scope_item', 'create_design_package_scope_item', 'update_design_package_scope_item', 'delete_design_package_scope_item',
            'view_any_design_package_activity', 'view_design_package_activity', 'create_design_package_activity', 'update_design_package_activity', 'delete_design_package_activity',
            'view_any_design_package_submission', 'view_design_package_submission', 'create_design_package_submission',
            'view_any_design_package_submission_document', 'view_design_package_submission_document', 'create_design_package_submission_document',
            'view_any_design_package_review', 'view_design_package_review', 'create_design_package_review',
            'view_any_design_review_finding', 'view_design_review_finding', 'create_design_review_finding',
            'view_any_design_package_revision', 'view_design_package_revision', 'create_design_package_revision',
            'view_any_design_revision_finding', 'view_design_revision_finding', 'create_design_revision_finding',
            'view_any_design_package_approval', 'view_design_package_approval', 'create_design_package_approval',
        ];

        foreach ($customDomainPermissions as $permission) {
            Permission::firstOrCreate(['name' => $permission, 'guard_name' => 'web']);
        }

        // 0. Super Admin role (Ensure it exists)
        Role::platform()->firstOrCreate(['name' => 'super_admin', 'guard_name' => 'web']);

        // 0b. Tenant role — used by the public /api/auth/register endpoint and
        // required by the `role:tenant` middleware guarding tenant-only API routes.
        // No Filament/Shield permissions attached: tenants never access the panel.
        Role::platform()->firstOrCreate(['name' => 'tenant', 'guard_name' => 'web']);

        // 1. Company Admin role
        $companyAdmin = Role::platform()->firstOrCreate(['name' => 'company_admin', 'guard_name' => 'web']);
        // Company admins can do almost everything within their company, except manage system-level roles
        $companyAdminPermissions = Permission::whereNotIn('name', [
            'view_role',
            'view_any_role',
            'create_role',
            'update_role',
            'delete_role',
            'delete_any_role',
            'force_delete_role',
            'force_delete_any_role',
            'reorder_role',
            'restore_role',
            'restore_any_role'
        ])->get();
        $companyAdmin->syncPermissions($companyAdminPermissions);

        // 2. Property Manager role
        $propertyManager = Role::platform()->firstOrCreate(['name' => 'property_manager', 'guard_name' => 'web']);
        $propertyManagerPermissions = Permission::where(function ($query) {
            $query->where('name', 'like', '%property%')
                ->orWhere('name', 'like', '%unit%')
                ->orWhere('name', 'like', '%image%')
                ->orWhere('name', 'like', '%maintenance%')
                ->orWhere('name', 'like', '%rental%')
                ->orWhere('name', 'like', '%location%');
        })->get();
        $propertyManager->syncPermissions($propertyManagerPermissions);

        // 3. Financial Manager role
        $financialManager = Role::platform()->firstOrCreate(['name' => 'financial_manager', 'guard_name' => 'web']);
        $financialManagerPermissions = Permission::where(function ($query) {
            $query->where('name', 'like', '%_lease')
                ->orWhere('name', 'like', '%_payment')
                ->orWhere('name', 'like', '%_expense')
                ->orWhere('name', 'like', '%_document')
                ->orWhere('name', 'like', '%_tenant')
                ->orWhere('name', 'like', '%_company');
        })->get();
        $financialManager->syncPermissions($financialManagerPermissions);
    }
}
