APP_NAME="Real Estate System PostgreSQL Tests"
APP_ENV=testing
APP_KEY=base64:u53KrUTrPKJB9tfiQ0z2cP3UppFPOK1ztd2WzkCtsJc=
APP_DEBUG=true
APP_URL=http://localhost

DB_CONNECTION=pgsql
DB_HOST=127.0.0.1
DB_PORT=6000
DB_DATABASE=realstate_pg_test
DB_USERNAME=postgres
DB_PASSWORD=password

CACHE_STORE=array
SESSION_DRIVER=array
QUEUE_CONNECTION=sync
MAIL_MAILER=array
BROADCAST_CONNECTION=null
FILESYSTEM_DISK=local
PULSE_ENABLED=false
TELESCOPE_ENABLED=false
NIGHTWATCH_ENABLED=false
