<?php
namespace Tests\Feature;
use App\Models\{Company,Location,Party,Property,PropertyAcquisition,User}; use App\Services\PropertyAcquisitionService; use Illuminate\Foundation\Testing\RefreshDatabase; use Illuminate\Support\Facades\Notification; use Spatie\Permission\Models\Permission; use Tests\TestCase;
class PropertyAcquisitionWorkflowTest extends TestCase {
 use RefreshDatabase;
 private function actor(Company $company,array $permissions):User { $u=User::factory()->create(['company_id'=>$company->id,'role'=>'company_admin']); foreach($permissions as $p){Permission::findOrCreate($p,'web');$u->givePermissionTo($p);} return $u; }
 private function property(Company $company):Property { $location=Location::withoutGlobalScopes()->create(['company_id'=>$company->id,'name'=>'Test city','type'=>'city']); return Property::withoutGlobalScopes()->create(['company_id'=>$company->id,'location_id'=>$location->id,'name'=>'Land','address'=>'Address']); }
 public function test_acquisition_accepts_multiple_same_tenant_properties_and_parties():void { $company=Company::create(['name'=>'A','email'=>'a@test.com']); $actor=$this->actor($company,['update_property_acquisition']); $a=PropertyAcquisition::withoutGlobalScopes()->create(['company_id'=>$company->id,'type'=>'cash_purchase']); $service=app(PropertyAcquisitionService::class); $service->attachProperty($actor,$a,$this->property($company)); $service->attachProperty($actor,$a,$this->property($company)); $party=Party::withoutGlobalScopes()->create(['company_id'=>$company->id,'type'=>'individual','name'=>'Seller']); $service->attachParty($actor,$a,$party,'seller'); $this->assertSame(2,$a->acquisitionProperties()->count()); $this->assertSame(1,$a->acquisitionParties()->count()); }
 public function test_cross_tenant_attachment_is_rejected():void { $a=Company::create(['name'=>'A','email'=>'a@test.com']);$b=Company::create(['name'=>'B','email'=>'b@test.com']);$actor=$this->actor($a,['update_property_acquisition']);$acq=PropertyAcquisition::withoutGlobalScopes()->create(['company_id'=>$a->id,'type'=>'cash_purchase']);$this->expectException(\Illuminate\Validation\ValidationException::class);app(PropertyAcquisitionService::class)->attachProperty($actor,$acq,$this->property($b)); }
 public function test_cancelled_acquisition_cannot_complete():void { $c=Company::create(['name'=>'A','email'=>'a@test.com']);$u=$this->actor($c,['cancel_property_acquisition','complete_property_acquisition']);$a=PropertyAcquisition::withoutGlobalScopes()->create(['company_id'=>$c->id,'type'=>'cash_purchase','status'=>'draft']);$s=app(PropertyAcquisitionService::class);$s->transition($u,$a,'cancelled','Stopped');$this->expectException(\Illuminate\Validation\ValidationException::class);$s->transition($u,$a->refresh(),'completed'); }
 public function test_ownership_replacement_preserves_history_and_requires_one_hundred_percent():void { $c=Company::create(['name'=>'A','email'=>'a@test.com']);$u=$this->actor($c,['change_property_ownership']);$p=$this->property($c);$one=Party::withoutGlobalScopes()->create(['company_id'=>$c->id,'type'=>'individual','name'=>'One']);$two=Party::withoutGlobalScopes()->create(['company_id'=>$c->id,'type'=>'individual','name'=>'Two']);$s=app(PropertyAcquisitionService::class);$s->replaceOwnership($u,$p,[['party'=>$one,'percentage'=>100]],'2026-01-01');$s->replaceOwnership($u,$p,[['party'=>$one,'percentage'=>60],['party'=>$two,'percentage'=>40]],'2026-02-01');$this->assertSame(2,$p->activeOwnerships()->count());$this->assertSame(3,$p->ownerships()->count()); }
 public function test_company_ownership_uses_a_reusable_company_party():void { $company=Company::create(['name'=>'Company Owner','email'=>'owner@test.com']);$property=$this->property($company);$service=app(PropertyAcquisitionService::class);$party=$service->partyForCompany($property,$company);$this->assertSame('company',$party->type);$this->assertSame($company->id,$party->company_id);$this->assertSame($party->id,$service->partyForCompany($property,$company)->id); }
 public function test_property_exposes_its_acquisition_history():void { $company=Company::create(['name'=>'A','email'=>'a@test.com']);$actor=$this->actor($company,['update_property_acquisition']);$property=$this->property($company);$acquisition=PropertyAcquisition::withoutGlobalScopes()->create(['company_id'=>$company->id,'type'=>'cash_purchase']);app(PropertyAcquisitionService::class)->attachProperty($actor,$acquisition,$property);$this->assertTrue($property->propertyAcquisitions()->whereKey($acquisition)->exists()); }
}
